services:
  gitlab-server:
    image: gitlab/gitlab-ce
    container_name: gitlab-server
    hostname: gitlab-server
    restart: always
    ports:
      - "8000:80"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['initial_root_password'] = "Shuaib@123456789"
        puma['worker_processes'] = 0
        external_url 'http://gitlab-server'
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab

  gitlab-runner:
    image: gitlab/gitlab-runner
    container_name: gitlab-runner
    restart: always
    depends_on:
      - gitlab-server
    volumes:
      - ./gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true